"""Write the demo environment (.env.demo) from .env.example: a separate compose project (``edisc-demo``)
on its own ports, so the demo never touches the dev or test stacks. EDISC_ENV=test makes it
disposable: the dev IdP is allowed and evidence locks for minutes, not years. ``scripts/demo.sh down``
destroys its volumes."""

from __future__ import annotations

import sys
from pathlib import Path

OVERRIDES = {
    "EDISC_ENV": "test",
    "EDISC_COMPOSE_PROJECT": "edisc-demo",
    "EDISC_PG_PORT": "25432",
    "EDISC_REDIS_PORT": "26379",
    "EDISC_REDIS_URL": "redis://localhost:26379/0",
    "EDISC_S3_PORT": "29000",
    "EDISC_S3_CONSOLE_PORT": "29001",
    "EDISC_S3_ENDPOINT": "http://localhost:29000",
    "EDISC_TEMPORAL_PORT": "27233",
    "EDISC_TEMPORAL_ADDRESS": "localhost:27233",
    "EDISC_TEMPORAL_UI_PORT": "28080",
    "EDISC_ES_PORT": "29200",
    "EDISC_ES_URL": "http://localhost:29200",
    "EDISC_S3_DEFAULT_RETENTION_DAYS": "0",
    "EDISC_EVIDENCE_RETENTION_OVERRIDE_SECONDS": "900",
    "EDISC_LOCAL_KMS_DIR": ".local-kms-demo",
    "EDISC_API_DEV_IDP": "true",
    # a killed worker's activities are retried elsewhere after this long (the demo resumes quickly)
    "EDISC_ACTIVITY_HEARTBEAT_TIMEOUT_SECONDS": "8",
}
DROP = {"EDISC_EVIDENCE_RETENTION_OVERRIDE_DAYS"}


def quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def main() -> None:
    example = Path(__file__).resolve().parents[1] / ".env.example"
    seen: set[str] = set()
    out = ["# GENERATED by scripts/demo_env.py: the disposable demo stack. Do not edit."]
    for raw in example.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        if key in DROP:
            continue
        seen.add(key)
        out.append(f"{key}={quote(OVERRIDES.get(key, value))}")
    out += [f"{k}={quote(v)}" for k, v in OVERRIDES.items() if k not in seen]
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
