"""Write the ephemeral integration-test environment (.env.test) from .env.example.

The test stack is a separate compose project (``edisc-test``) on different host ports, so test evidence
never touches the dev stack. Its volumes are destroyed after every run (``make test-integration``).
Only here may evidence be locked for seconds (EDISC_ENV=test).
"""

from __future__ import annotations

import sys
from pathlib import Path

OVERRIDES = {
    "EDISC_ENV": "test",
    "EDISC_COMPOSE_PROJECT": "edisc-test",
    "EDISC_PG_PORT": "15432",
    "EDISC_REDIS_PORT": "16379",
    "EDISC_REDIS_URL": "redis://localhost:16379/0",
    "EDISC_S3_PORT": "19000",
    "EDISC_S3_CONSOLE_PORT": "19001",
    "EDISC_S3_ENDPOINT": "http://localhost:19000",
    "EDISC_TEMPORAL_PORT": "17233",
    "EDISC_TEMPORAL_ADDRESS": "localhost:17233",
    "EDISC_TEMPORAL_UI_PORT": "18080",
    "EDISC_ES_PORT": "19200",
    "EDISC_ES_URL": "http://localhost:19200",
    "EDISC_S3_DEFAULT_RETENTION_DAYS": "0",  # no day-level bucket default: objects lock for seconds
    "EDISC_EVIDENCE_RETENTION_OVERRIDE_SECONDS": "600",
    "EDISC_FILE_RETRY_BACKOFF_SECONDS": "0.01",  # speed only; the attempt count is unchanged
}
DROP = {"EDISC_EVIDENCE_RETENTION_OVERRIDE_DAYS"}


def quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def main() -> None:
    example = Path(__file__).resolve().parents[1] / ".env.example"
    seen: set[str] = set()
    out = [
        "# GENERATED by scripts/make_test_env.py from .env.example: ephemeral test stack. Do not edit."
    ]
    for raw in example.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        if key in DROP:
            continue
        seen.add(key)
        out.append(f"{key}={quote(OVERRIDES.get(key, value))}")
    out += [f"{k}={quote(v)}" for k, v in OVERRIDES.items() if k not in seen]
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
