"""The report fonts' glyph coverage (ADR 0018 §5.5): the union of the cmaps of the vendored fonts, as
code point ranges, committed as `edisc_renderers/report/fonts/coverage.txt` so the PURE HTML builder
can replace every character no vendored font draws by its marker without having the fonts.

    uv run --with fonttools python scripts/report_font_coverage.py --write FONT_DIR   # regenerate
    python scripts/report_font_coverage.py --check /opt/edisc/fonts                   # in the image

FONT_DIR holds the files of `deploy/report-image/fonts.lock` (as fetched, or instanced: instancing a
variable font does not change its cmap; the in-image check proves it on the installed files). The
header lists the lock lines the coverage was computed from; a unit test ties it to `fonts.lock`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
LOCK = REPO / "deploy" / "report-image" / "fonts.lock"
COVERAGE = REPO / "packages/renderers/src/edisc_renderers/report/fonts/coverage.txt"


def lock_fonts(lock: Path = LOCK) -> list[tuple[str, str]]:
    """(name, sha256) of every VENDORED font in fonts.lock (not the leak probe, not licences)."""
    out = []
    for line in lock.read_text().splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        name, sha, _ = line.split()
        if "/" not in name:
            out.append((name, sha))
    return out


def compute(font_dir: Path) -> list[tuple[int, int]]:
    from fontTools.ttLib import TTFont

    cps: set[int] = set()
    for f in sorted(font_dir.glob("*.ttf")):
        cps |= set(TTFont(f, lazy=True).getBestCmap())
    ranges: list[tuple[int, int]] = []
    for cp in sorted(cps):
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], cp)
        else:
            ranges.append((cp, cp))
    return ranges


def render(ranges: list[tuple[int, int]], fonts: list[tuple[str, str]]) -> str:
    head = [
        "# edisc collection report: glyph coverage of the vendored fonts (ADR 0018 §5.5).",
        "# Generated by scripts/report_font_coverage.py; do not edit. Computed from fonts.lock:",
        *(f"# font {name} {sha}" for name, sha in fonts),
        f"# {sum(hi - lo + 1 for lo, hi in ranges)} code points in {len(ranges)} ranges",
    ]
    body = [f"{lo:04X}-{hi:04X}" if hi != lo else f"{lo:04X}" for lo, hi in ranges]
    return "\n".join(head + body) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", type=Path, metavar="FONT_DIR")
    mode.add_argument("--check", type=Path, metavar="FONT_DIR")
    args = ap.parse_args()
    text = render(compute(args.write or args.check), lock_fonts())
    if args.write:
        COVERAGE.write_text(text)
        print(f"wrote {COVERAGE}")
        return 0
    if COVERAGE.read_text() != text:
        print(f"FAIL: {COVERAGE} differs from the coverage of {args.check}", file=sys.stderr)
        return 1
    print(f"OK: {COVERAGE.name} equals the coverage of {args.check}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
