/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_v1_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_v1_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_v1_clients__client_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{client_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Client
         * @description Its matters must be closed first. Its validated exports stop being extended. Reversible by a
         *     tenant admin (``.../reopen``).
         */
        post: operations["close_client_v1_clients__client_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{client_id}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Client Connections */
        get: operations["list_client_connections_v1_clients__client_id__connections_get"];
        put?: never;
        /** Create Connection */
        post: operations["create_connection_v1_clients__client_id__connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{client_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_v1_clients__client_id__exports_get"];
        put?: never;
        /** Create Export */
        post: operations["create_export_v1_clients__client_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{client_id}/matters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matters */
        get: operations["list_matters_v1_clients__client_id__matters_get"];
        put?: never;
        /** Create Matter */
        post: operations["create_matter_v1_clients__client_id__matters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{client_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reopen Client
         * @description Tenant admins only, audited. Its matters stay closed until reopened themselves; its validated
         *     exports are protected again at once (lapsed ones re-locked if they still exist, gaps recorded).
         */
        post: operations["reopen_client_v1_clients__client_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{client_id}/retention-gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Client Retention Gaps
         * @description Every window in which a client-level export was not under retention (ADR 0002).
         */
        get: operations["client_retention_gaps_v1_clients__client_id__retention_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["get_connection_v1_connections__connection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{connection_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable */
        post: operations["disable_v1_connections__connection_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{connection_id}/reauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthorize */
        post: operations["reauthorize_v1_connections__connection_id__reauth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{evidence_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evidence Content
         * @description The pinned evidence bytes. The audit event is committed BEFORE any byte is returned (ADR 0013
         *     decision d): a read that is not recorded never happens.
         */
        get: operations["evidence_content_v1_evidence__evidence_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/{export_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export */
        get: operations["get_export_v1_exports__export_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/{export_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Export */
        post: operations["complete_export_v1_exports__export_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/{export_id}/parts/{part_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Part */
        put: operations["upload_part_v1_exports__export_id__parts__part_number__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Group */
        post: operations["create_group_v1_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Member */
        post: operations["add_member_v1_groups__group_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{group_id}/members/{principal_id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove Member */
        post: operations["remove_member_v1_groups__group_id__members__principal_id__remove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/custody/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify */
        get: operations["verify_v1_jobs__job_id__custody_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reconciliation */
        get: operations["reconciliation_v1_jobs__job_id__reconciliation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun Job
         * @description Re-run the failed units of a finished job as a NEW job (the sealed original stays closed).
         */
        post: operations["rerun_job_v1_jobs__job_id__rerun_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Job
         * @description Ask the job to re-check its state now (e.g. after retry_later cool-downs or an operator fix). A
         *     job paused for re-authorization resumes only through the connection's re-authorization.
         */
        post: operations["resume_job_v1_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Units */
        get: operations["list_units_v1_jobs__job_id__units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matters/{matter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Matter */
        get: operations["get_matter_v1_matters__matter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matters/{matter_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Matter
         * @description No new jobs; the retention-extension job stops extending this matter's evidence, which then
         *     expires on schedule. Running jobs must be finished or cancelled first (and, once legal hold exists,
         *     a held matter cannot close). Reversible by a tenant admin (``.../reopen``).
         */
        post: operations["close_matter_v1_matters__matter_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matters/{matter_id}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matter Connections
         * @description The client's connections a job on this matter may use (decision a: matters reference them).
         */
        get: operations["list_matter_connections_v1_matters__matter_id__connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matters/{matter_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_v1_matters__matter_id__jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_v1_matters__matter_id__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matters/{matter_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reopen Matter
         * @description Tenant admins only, audited. Retention extension resumes at once; evidence whose retention lapsed
         *     while closed is re-locked if it still exists, and every unprotected window is recorded
         *     (``GET .../retention-gaps``).
         */
        post: operations["reopen_matter_v1_matters__matter_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matters/{matter_id}/retention-gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Matter Retention Gaps
         * @description Every window in which evidence of this matter was not under retention (ADR 0002).
         */
        get: operations["matter_retention_gaps_v1_matters__matter_id__retention_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matters/{matter_id}/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_v1_matters__matter_id__workspaces_get"];
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_v1_matters__matter_id__workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/principals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Principals */
        get: operations["list_principals_v1_principals_get"];
        put?: never;
        /** Create Principal */
        post: operations["create_principal_v1_principals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/principals/{principal_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Principal */
        post: operations["deactivate_principal_v1_principals__principal_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/role-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignments */
        get: operations["list_assignments_v1_role_assignments_get"];
        put?: never;
        /** Assign Role */
        post: operations["assign_role_v1_role_assignments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/role-assignments/{assignment_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Role */
        post: operations["revoke_role_v1_role_assignments__assignment_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignmentIn */
        AssignmentIn: {
            /** Group Id */
            group_id?: string | null;
            /** Principal Id */
            principal_id?: string | null;
            /** Role */
            role: string;
            /** Scope Id */
            scope_id?: string | null;
            /**
             * Scope Type
             * @enum {string}
             */
            scope_type: "tenant" | "client" | "matter" | "workspace";
        };
        /** AssignmentOut */
        AssignmentOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Group Id */
            group_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Principal Id */
            principal_id: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Revoked By */
            revoked_by: string | null;
            /** Role */
            role: string;
            /** Scope Id */
            scope_id: string | null;
            /** Scope Type */
            scope_type: string;
        };
        /** ClientIn */
        ClientIn: {
            /** Name */
            name: string;
        };
        /** ClientOut */
        ClientOut: {
            /** Closed At */
            closed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Default */
            is_default: boolean;
            /** Name */
            name: string;
        };
        /** ConnectionIn */
        ConnectionIn: {
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            credentials: components["schemas"]["Credentials"];
            /** External Org Id */
            external_org_id: string;
            /** Source */
            source: string;
        };
        /** ConnectionOut */
        ConnectionOut: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** External Org Id */
            external_org_id: string;
            /** Granted Scopes */
            granted_scopes: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Plan Tier */
            plan_tier: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Credentials */
        Credentials: {
            /**
             * Access Token
             * Format: password
             */
            access_token: string;
            /** Expires At */
            expires_at?: string | null;
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /** ExportIn */
        ExportIn: {
            limits?: components["schemas"]["LimitOverrides"] | null;
            /** Plan */
            plan?: string | null;
            /** Sha256 */
            sha256?: string | null;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ExportOut */
        ExportOut: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Connection Id */
            connection_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Declared Plan */
            declared_plan: string | null;
            /** Declared Sha256 */
            declared_sha256: string | null;
            /** Declared Size */
            declared_size: number;
            /** Detected Tier */
            detected_tier: string | null;
            /** Entry Count */
            entry_count: number | null;
            /** Evidence Object Id */
            evidence_object_id: string | null;
            /** Findings */
            findings: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Limits */
            limits: {
                [key: string]: number;
            };
            /** Locked At */
            locked_at: string | null;
            /** Reject Detail */
            reject_detail: {
                [key: string]: unknown;
            } | null;
            /** Reject Reason */
            reject_reason: string | null;
            /** Root Prefix */
            root_prefix: string | null;
            /** Sha256 */
            sha256: string | null;
            /** Size Bytes */
            size_bytes: number | null;
            /** Status */
            status: string;
            /** Tier Confirmed */
            tier_confirmed: boolean | null;
            upload: components["schemas"]["UploadInfo"] | null;
            /** Validated At */
            validated_at: string | null;
            /** Version Id */
            version_id: string | null;
            /** Workspace Id */
            workspace_id: string | null;
        };
        /** GroupIn */
        GroupIn: {
            /** External Id */
            external_id?: string | null;
            /** Name */
            name: string;
        };
        /** GroupOut */
        GroupOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** External Id */
            external_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobIn */
        JobIn: {
            /**
             * Connection Id
             * Format: uuid
             */
            connection_id: string;
            /** Scopes */
            scopes: components["schemas"]["ScopeIn"][];
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /** JobOut */
        JobOut: {
            /** Caveat */
            caveat: string | null;
            /** Clean */
            clean: boolean;
            /** Clean Basis */
            clean_basis: string | null;
            /**
             * Connection Id
             * Format: uuid
             */
            connection_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Matter Id
             * Format: uuid
             */
            matter_id: string;
            /** Paused Ms */
            paused_ms: number | null;
            /** Requested By */
            requested_by: string;
            /** Rerun Of */
            rerun_of: string | null;
            /** Scopes */
            scopes: components["schemas"]["ScopeOut"][];
            /** Sealed */
            sealed: boolean;
            /** Status */
            status: string;
            /** Units */
            units: {
                [key: string]: number;
            };
            /** Workspace Id */
            workspace_id: string | null;
        };
        /** LimitOverrides */
        LimitOverrides: {
            /** Max Archive Bytes */
            max_archive_bytes?: number | null;
            /** Max Entries */
            max_entries?: number | null;
            /** Max Entry Bytes */
            max_entry_bytes?: number | null;
            /** Max Entry Ratio */
            max_entry_ratio?: number | null;
            /** Max Name Bytes */
            max_name_bytes?: number | null;
            /** Max Total Bytes */
            max_total_bytes?: number | null;
            /** Max Total Ratio */
            max_total_ratio?: number | null;
            /** Ratio Floor Bytes */
            ratio_floor_bytes?: number | null;
        };
        /** MatterIn */
        MatterIn: {
            /** Name */
            name: string;
            /**
             * Retention Until
             * Format: date-time
             */
            retention_until: string;
        };
        /** MatterOut */
        MatterOut: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Closed At */
            closed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Retention Until
             * Format: date-time
             */
            retention_until: string;
        };
        /** Me */
        Me: {
            /** Issuer */
            issuer: string;
            /** Kind */
            kind: string;
            /**
             * Principal Id
             * Format: uuid
             */
            principal_id: string;
            /** Subject */
            subject: string;
        };
        /** MemberIn */
        MemberIn: {
            /**
             * Principal Id
             * Format: uuid
             */
            principal_id: string;
        };
        /** Page[AssignmentOut] */
        Page_AssignmentOut_: {
            /** Items */
            items: components["schemas"]["AssignmentOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[ClientOut] */
        Page_ClientOut_: {
            /** Items */
            items: components["schemas"]["ClientOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[ConnectionOut] */
        Page_ConnectionOut_: {
            /** Items */
            items: components["schemas"]["ConnectionOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[ExportOut] */
        Page_ExportOut_: {
            /** Items */
            items: components["schemas"]["ExportOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[JobOut] */
        Page_JobOut_: {
            /** Items */
            items: components["schemas"]["JobOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[MatterOut] */
        Page_MatterOut_: {
            /** Items */
            items: components["schemas"]["MatterOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[PrincipalOut] */
        Page_PrincipalOut_: {
            /** Items */
            items: components["schemas"]["PrincipalOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[RetentionGapOut] */
        Page_RetentionGapOut_: {
            /** Items */
            items: components["schemas"]["RetentionGapOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[UnitOut] */
        Page_UnitOut_: {
            /** Items */
            items: components["schemas"]["UnitOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[WorkspaceOut] */
        Page_WorkspaceOut_: {
            /** Items */
            items: components["schemas"]["WorkspaceOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** PartOut */
        PartOut: {
            /** Part Number */
            part_number: number;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** PrincipalIn */
        PrincipalIn: {
            /** Display Name */
            display_name: string;
            /** Email */
            email?: string | null;
            /** Issuer */
            issuer: string;
            /**
             * Kind
             * @default user
             * @enum {string}
             */
            kind: "user" | "service";
            /** Subject */
            subject: string;
        };
        /** PrincipalOut */
        PrincipalOut: {
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issuer */
            issuer: string;
            /** Kind */
            kind: string;
            /** Subject */
            subject: string;
        };
        /** ReauthIn */
        ReauthIn: {
            credentials: components["schemas"]["Credentials"];
        };
        /** ReconciliationOut */
        ReconciliationOut: {
            /** By Recon Status */
            by_recon_status: {
                [key: string]: number;
            };
            /** Caveat */
            caveat: string | null;
            /** Clean */
            clean: boolean;
            /** Clean Basis */
            clean_basis: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Not Matched */
            not_matched: components["schemas"]["UnitOut"][];
            /** Status */
            status: string;
        };
        /** ReopenIn */
        ReopenIn: {
            /** Retention Until */
            retention_until?: string | null;
        };
        /** RetentionGapOut */
        RetentionGapOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Evidence Object Id
             * Format: uuid
             */
            evidence_object_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Outcome */
            outcome: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Owner Type */
            owner_type: string;
            /**
             * Unprotected From
             * Format: date-time
             */
            unprotected_from: string;
            /**
             * Unprotected Until
             * Format: date-time
             */
            unprotected_until: string;
        };
        /** ScopeIn */
        ScopeIn: {
            /**
             * Date From
             * Format: date-time
             */
            date_from: string;
            /**
             * Date To
             * Format: date-time
             */
            date_to: string;
            /** External Id */
            external_id: string;
            /** @default include_parent_and_thread */
            thread_parent_policy: components["schemas"]["ThreadParentPolicy"];
            /**
             * Type
             * @enum {string}
             */
            type: "channel" | "custodian";
        };
        /** ScopeOut */
        ScopeOut: {
            /**
             * Date From
             * Format: date-time
             */
            date_from: string;
            /**
             * Date To
             * Format: date-time
             */
            date_to: string;
            /** External Id */
            external_id: string;
            /** Thread Parent Policy */
            thread_parent_policy: string;
            /** Type */
            type: string;
        };
        /**
         * ThreadParentPolicy
         * @description What to collect for thread replies that are INSIDE the date range while their parent is OUTSIDE.
         *
         *     PROPOSED default, pending product-owner confirmation (docs/adr/0011): include the parent and the
         *     full thread, with everything outside the range marked out-of-range (context, not responsive scope).
         * @enum {string}
         */
        ThreadParentPolicy: "include_parent_and_thread" | "include_parent_only" | "replies_only";
        /** UnitOut */
        UnitOut: {
            /** Caveat */
            caveat: string | null;
            /** Collected Count */
            collected_count: number;
            /** Day Anomalies */
            day_anomalies: number;
            /** Expected Count */
            expected_count: number | null;
            /** File Gaps */
            file_gaps: number;
            /** Kind */
            kind: string;
            /** Last Error */
            last_error: string | null;
            /** Recon Status */
            recon_status: string;
            /** Status */
            status: string;
            /** Unit Key */
            unit_key: string;
        };
        /** UploadInfo */
        UploadInfo: {
            /** Bytes Received */
            bytes_received: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Part Max Bytes */
            part_max_bytes: number;
            /** Part Min Bytes */
            part_min_bytes: number;
            /** Parts Received */
            parts_received: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyOut */
        VerifyOut: {
            /** Anchors Checked */
            anchors_checked: number;
            /** Batches Checked */
            batches_checked: number;
            /** Errors */
            errors: string[];
            /** Events */
            events: number;
            /** Items Checked */
            items_checked: number;
            /** Ok */
            ok: boolean;
        };
        /** WorkspaceIn */
        WorkspaceIn: {
            /** Name */
            name: string;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Matter Id
             * Format: uuid
             */
            matter_id: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_clients_v1_clients_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ClientOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_v1_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_v1_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_client_v1_clients__client_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_client_connections_v1_clients__client_id__connections_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ConnectionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_connection_v1_clients__client_id__connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exports_v1_clients__client_id__exports_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ExportOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_v1_clients__client_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matters_v1_clients__client_id__matters_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MatterOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_matter_v1_clients__client_id__matters_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_client_v1_clients__client_id__reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_retention_gaps_v1_clients__client_id__retention_gaps_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RetentionGapOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_v1_connections__connection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_v1_connections__connection_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reauthorize_v1_connections__connection_id__reauth_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReauthIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_content_v1_evidence__evidence_id__content_get: {
        parameters: {
            query: {
                purpose: "preview" | "download" | "export" | "rsmf";
            };
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_export_v1_exports__export_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_export_v1_exports__export_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_part_v1_exports__export_id__parts__part_number__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
                part_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_v1_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_v1_groups__group_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_v1_groups__group_id__members__principal_id__remove_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                principal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_v1_jobs__job_id__custody_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconciliation_v1_jobs__job_id__reconciliation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_job_v1_jobs__job_id__rerun_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_v1_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_units_v1_jobs__job_id__units_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UnitOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_matter_v1_matters__matter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_matter_v1_matters__matter_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matter_connections_v1_matters__matter_id__connections_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ConnectionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_v1_matters__matter_id__jobs_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_v1_matters__matter_id__jobs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_matter_v1_matters__matter_id__reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReopenIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matter_retention_gaps_v1_matters__matter_id__retention_gaps_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RetentionGapOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_v1_matters__matter_id__workspaces_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_WorkspaceOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_v1_matters__matter_id__workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    list_principals_v1_principals_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PrincipalOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_principal_v1_principals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrincipalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_principal_v1_principals__principal_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                principal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assignments_v1_role_assignments_get: {
        parameters: {
            query?: {
                /** @description opaque cursor from the previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AssignmentOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_role_v1_role_assignments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_role_v1_role_assignments__assignment_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
